### ISSUE TITLE
make valid-point? a public fn

### ISSUE THREAD

**Issue by thedavidmeister** [Sepia-Officinalis/secp256k1#25]
helps with testing, etc.

**Comment by xcthulhu** [comment]
It is not public in the spec namespace:

https://github.com/Sepia-Officinalis/secp256k1/blob/efac754d06f6ee9404de53b587d322afc8f43378/src/cljc/secp256k1/spec.cljc#L10

**Comment by xcthulhu** [comment]
(thank you for your contribution @thedavidmeister !)
